param([switch]$Rollback,[string]$TargetDirectory="")
$ErrorActionPreference="Stop"
$Root=$PSScriptRoot
$Runtime=Join-Path $env:LOCALAPPDATA "CEREBRO\browser-bridge"
$Record=Join-Path $Runtime "accessboot-v0.json"
$Report=[ordered]@{record_type="cerebro_accessboot_windows_operator";package_version="v0";status="ERROR";stage="INIT";target="";backup="";checks=[ordered]@{};next_gate="";error="";prod_enabled=$false}
function Save-Report {New-Item -ItemType Directory -Force -Path $Runtime|Out-Null;($Report|ConvertTo-Json -Depth 8)|Set-Content -LiteralPath $Record -Encoding UTF8;$Report|ConvertTo-Json -Depth 8}
function Stop-Cerebro {foreach($p in @(Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe'")){$c=[string]$p.CommandLine;if($c -match '(?i)(CerebroBrowserBridgeService|CerebroBrowserTransport)\.ps1' -and $c -notmatch '(?i)Install-CerebroAccessboot'){Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue}}}
function Copy-Managed([string]$From,[string]$To){Copy-Item -LiteralPath (Join-Path $From "CerebroBrowserBridgeService.ps1") -Destination (Join-Path $To "CerebroBrowserBridgeService.ps1") -Force;Copy-Item -LiteralPath (Join-Path $From "CerebroBrowserTransport.ps1") -Destination (Join-Path $To "CerebroBrowserTransport.ps1") -Force;New-Item -ItemType Directory -Force -Path (Join-Path $To "chrome_extension_v1_4_1")|Out-Null;Copy-Item -LiteralPath (Join-Path $From "chrome_extension_v1_4_1\manifest.json") -Destination (Join-Path $To "chrome_extension_v1_4_1\manifest.json") -Force;Copy-Item -LiteralPath (Join-Path $From "chrome_extension_v1_4_1\service_worker.js") -Destination (Join-Path $To "chrome_extension_v1_4_1\service_worker.js") -Force}
try{
 if($Rollback){if(-not(Test-Path $Record)){throw "ROLLBACK_STATE_MISSING"};$old=Get-Content -Raw $Record|ConvertFrom-Json;if(-not $old.backup -or -not $old.target){throw "ROLLBACK_POINTER_MISSING"};Stop-Cerebro;Copy-Managed ([string]$old.backup) ([string]$old.target);& (Join-Path ([string]$old.target) "Start-CerebroBrowserBridge.ps1")|Out-Null;$Report.status="ROLLED_BACK";$Report.stage="RESTORED";$Report.target=[string]$old.target;$Report.backup=[string]$old.backup;$Report.next_gate="RELOAD_PREVIOUS_EXTENSION";Save-Report;exit 0}
 $Report.stage="INVENTORY";$v162=Join-Path $Runtime "recovery-v1.6.2.json";if(-not(Test-Path $v162)){throw "V162_RECORD_MISSING"};$prior=Get-Content -Raw $v162|ConvertFrom-Json
 $Target=if($TargetDirectory){(Resolve-Path $TargetDirectory).Path}else{[string]$prior.target};if(-not(Test-Path $Target)){throw "BRIDGE_TARGET_MISSING"};$Report.target=$Target
 $health=$null;foreach($port in 8765..8785){try{$h=Invoke-RestMethod "http://127.0.0.1:$port/health" -TimeoutSec 1;if($h.service -eq "CEREBRO Browser Bridge" -and $h.company_id -eq "fenix" -and $h.environment -eq "LAB" -and -not [bool]$h.prod_allowed){$health=$h;break}}catch{}}
 if(-not $health){throw "TRUSTED_LAB_BRIDGE_NOT_FOUND"};$Report.checks.existing_bridge=$true;$Report.checks.paired=[bool]$health.paired;$Report.checks.kill_switch=[bool]$health.kill_switch_enabled;if(-not $Report.checks.paired -or -not $Report.checks.kill_switch){throw "BRIDGE_NOT_SAFE"}
 $Report.stage="VERIFY_PAYLOAD";$payload=Join-Path $Root "payload";foreach($f in @("CerebroBrowserBridgeService.ps1","CerebroBrowserTransport.ps1","chrome_extension_v1_4_1\manifest.json","chrome_extension_v1_4_1\service_worker.js")){if(-not(Test-Path (Join-Path $payload $f))){throw "PAYLOAD_FILE_MISSING"}}
 $m=Get-Content -Raw (Join-Path $payload "chrome_extension_v1_4_1\manifest.json")|ConvertFrom-Json;if($m.version -ne "1.7.0" -or "https://*/*" -notin @($m.host_permissions) -or "tabs" -notin @($m.permissions)){throw "EXTENSION_CAPABILITY_MISMATCH"}
 $Report.checks.extension_v170=$true;$Report.checks.lab_only=$true;$Report.checks.prod_disabled=$true
 $Report.stage="SNAPSHOT";$Backup=Join-Path $Runtime ("accessboot-backup-v0-"+(Get-Date -Format "yyyyMMdd-HHmmss"));New-Item -ItemType Directory -Force -Path $Backup|Out-Null;$Report.backup=$Backup
 foreach($f in @("CerebroBrowserBridgeService.ps1","CerebroBrowserTransport.ps1")){Copy-Item (Join-Path $Target $f) (Join-Path $Backup $f) -Force};New-Item -ItemType Directory -Force -Path (Join-Path $Backup "chrome_extension_v1_4_1")|Out-Null;Copy-Item (Join-Path $Target "chrome_extension_v1_4_1\*") (Join-Path $Backup "chrome_extension_v1_4_1") -Force;Save-Report|Out-Null
 $Report.stage="INSTALL";Stop-Cerebro;Copy-Managed $payload $Target
 $Report.stage="START";$env:CEREBRO_BRIDGE_PORT="8766";& (Join-Path $Target "Start-CerebroBrowserBridge.ps1")|Out-Null
 $Report.status="PARTIAL";$Report.stage="INSTALLED";$Report.next_gate="RELOAD_EXISTING_EXTENSION_ONCE_THEN_CLOUD_FS_AND_YOUTUBE_ACCEPTANCE";Save-Report;exit 0
}catch{$Report.error=$_.Exception.Message;if($Report.backup -and $Report.target -and $Report.stage -in @("INSTALL","START")){try{Stop-Cerebro;Copy-Managed $Report.backup $Report.target;& (Join-Path $Report.target "Start-CerebroBrowserBridge.ps1")|Out-Null;$Report.status="ROLLED_BACK";$Report.next_gate="RELOAD_PREVIOUS_EXTENSION"}catch{$Report.status="ERROR";$Report.next_gate="MANUAL_RECOVERY_REQUIRED"}};Save-Report;exit 1}
