from __future__ import annotations

OBJECTIVES = {
    "APP_001_inventory": "GREEN",
    "CRM_001_inventory": "GREEN",
    "APP_002_auth_rpc_security": "PARTIAL_SOURCE_PROMOTED_CALLERS_ZERO_HTTP_AUTH_E2E_AND_SELECTIVE_RETIREMENT_OPEN",
    "APP_003_expedientes": "GREEN_PROMOTED_SOURCE_AND_LIVE_RPC_PARITY_HTTP_E2E_SUBGAP",
    "APP_004_tasks_notifications": "GREEN_PROMOTED_SOURCE_AND_LIVE_RPC_PARITY_HTTP_E2E_SUBGAP",
    "APP_005_documents": "GREEN",
    "APP_006_signatures": "GREEN_PROMOTED_SOURCE_AND_LIVE_RPC_PARITY_HTTP_E2E_SUBGAP",
    "APP_007_communications": "GREEN_CORE_GATEWAY_WITH_OPTIONAL_ADVICE_FAIL_SOFT",
    "APP_008_reports": "GREEN",
    "CRM_002_sync_consistency": "GREEN_LEGACY_SYNC_RETIRED_FAIL_CLOSED",
    "APP_009_carlos_cerebro_access": "PARTIAL_PROMOTED_INTERNAL_LAUNCHER_DEPLOYED_CONSOLE_GATEWAY_URL_MISSING",
    "APP_010_cerebro_gateway": "PARTIAL_HTTP_AND_WEB_UI_GREEN_DEPLOYED_AUTHENTICATED_URL_MISSING",
    "APP_011_old_new_rollback_promotion": "PARTIAL_SOURCE_PROMOTION_GREEN_HTTP_E2E_ROLLBACK_AND_PRIVILEGE_RETIREMENT_OPEN",
}

BLOCKERS = {
    "rpc_live_migration": {
        "authorized": True,
        "remaining_server_wrappers": 0,
        "server_wrappers_live": True,
        "server_wrappers_security_definer": True,
        "server_wrappers_service_role_only": True,
        "unknown_actor_fail_closed_all_five": True,
        "null_actor_guard_migration": "harden_server_wrappers_null_actor_guard_20260914",
        "exp_create_null_actor_guard": True,
        "sign_create_null_actor_guard": True,
        "app_gateway_live_version": 17,
        "app_gateway_required_routes_live": True,
        "runner_direct_callers_before": 10,
        "runner_direct_callers_after": 0,
        "persisted_branch_direct_callers_zero": True,
        "live_deploy_channel": "GITHUB_PAGES_GH_PAGES",
        "live_deployed_source_sha": "dd09153a6d025d9cc75eb2c14e776a9e5bd8e16c",
        "live_deployed_snapshot_sha": "c8a4bc720ce91eb46ed811c506623c265d043594",
        "live_deploy_run": 34790008072,
        "live_deploy_success": True,
        "live_deployed_app_is_pre_rpc_migration_branch": False,
        "live_direct_callers_zero_proven": True,
        "live_rpc_old_new_parity_proven": True,
        "live_rpc_old_new_parity_transaction_rolled_back": True,
        "live_rpc_old_new_parity_cases": (
            "notifications_list",
            "notification_mark",
            "contact_create",
            "exp_create",
            "sign_create",
        ),
        "live_gateway_http_health_proven": True,
        "live_gateway_http_health_status": 200,
        "live_gateway_unauthenticated_target_fail_closed": True,
        "live_gateway_unauthenticated_target_status": 401,
        "live_gateway_http_e2e_proven": False,
        "http_write_path_rollback_proven": False,
        "safe_test_identity_available": False,
        "authenticated_execute_revoke_allowed": False,
        "legacy_retirement_sql_prepared": True,
        "legacy_retirement_applied": False,
        "branch_persisted_migrations": {
            "notifications_list": True,
            "notification_mark": True,
            "signature_create": True,
            "contact_create": True,
            "expediente_create": True,
            "branch_head": "b1b6fb5404a4704c5d637fc770fc90e9f2eb8312",
            "audit_ci_run": 34786441006,
            "audit_ci_success": True,
            "main_modified": True,
            "main_merge_sha": "dd09153a6d025d9cc75eb2c14e776a9e5bd8e16c",
            "legacy_authenticated_execute_revoked": False,
        },
        "pull_request": {
            "number": 376,
            "state": "MERGED",
            "mergeable_before_merge": True,
            "base": "main",
            "head": "cerebro-app-crm-rpc-migration-v0-20260913",
            "head_sha": "b1b6fb5404a4704c5d637fc770fc90e9f2eb8312",
            "merge_sha": "dd09153a6d025d9cc75eb2c14e776a9e5bd8e16c",
            "promotion_human_gate_satisfied": True,
        },
        "parallel_hosting": {
            "cloudflare_workers_builds_success": True,
            "cloudflare_pages_check_success": False,
            "cloudflare_pages_routing_role_proven": False,
            "safe_disposition": "PRESERVE_AND_AUDIT_ROUTING_BEFORE_CHANGE",
        },
    },
    "communications": {
        "prod_gateway_exists": True,
        "prod_gateway_version": 8,
        "app_shell_targets_prod_gateway": True,
        "prepare_send_contract_aligned": True,
        "real_send_path_owned_by_gateway": True,
        "real_send_providers": ("brevo", "whatsapp"),
        "assistant_dependency": "fenix-expediente-assistant-test",
        "assistant_present_in_current_prod_edge_inventory": False,
        "assistant_is_optional_draft_enrichment_only": True,
        "assistant_failure_is_fail_soft": True,
        "communications_core_operational_without_assistant": True,
        "prod_ana_api_present": True,
        "prod_ana_api_scope": "capabilities_and_corrections_not_expediente_advice",
        "prod_ana_canonical_present": True,
        "prod_ana_canonical_scope": "canonical_rules_reader_not_expediente_advice",
        "real_send_claimed": False,
    },
    "supabase_security_advisor": {
        "observed_at": "2026-09-13T23:39:42.503Z",
        "rls_enabled_no_policy_count": 44,
        "rls_enabled_no_policy_level": "INFO",
        "rls_tables_are_currently_fail_closed_for_direct_table_access": True,
        "security_definer_authenticated_executable_count": 24,
        "security_definer_authenticated_executable_level": "WARN",
        "bulk_revoke_allowed": False,
        "legacy_rpc_retirement_requires_live_app_caller_zero": True,
        "live_app_caller_zero_now_proven": True,
        "legacy_rpc_retirement_also_requires_authenticated_http_e2e": True,
        "pg_net_extension_schema": "public",
        "pg_net_extension_version": "0.20.4",
        "pg_net_functions_namespace": "net",
        "pg_net_move_without_dependency_backup_review_allowed": False,
        "leaked_password_protection_enabled": False,
        "leaked_password_protection_level": "WARN",
        "auth_config_write_channel_available": False,
        "status": "SOURCE_MIGRATION_GREEN_HTTP_E2E_REQUIRED_BEFORE_SELECTIVE_RETIREMENT",
    },
    "cerebro_console": {
        "logical_gateway_contract_green": True,
        "http_surface_green": True,
        "pipeline_audit_path_green": True,
        "trusted_upstream_identity_boundary_green": True,
        "browser_identity_header_trusted": False,
        "app_profile_surface_found": True,
        "internal_console_route_present": True,
        "internal_console_route": "/cerebro",
        "promoted_internal_console_route": True,
        "profile_launcher_present": True,
        "web_shell_fail_closed_without_gateway_url": True,
        "deployed_authenticated_console_url_proven": False,
        "deployed_profile_launcher_to_external_gateway_proven": False,
        "dead_link_allowed": False,
    },
    "credential_registry": {
        "metadata_only_registry_present": True,
        "raw_secret_fields_forbidden_by_validator": True,
        "opaque_provider_managed_credentials_supported": True,
        "vault_refs_supported": True,
        "raw_values_in_registry_allowed": False,
    },
    "global_pre_app_closure": {
        "security_global_green": False,
        "recovery_global_green": False,
        "observability_global_green": False,
        "finops_global_green": False,
        "promotion_human_gate_required": True,
    },
}


def assess() -> dict:
    fully_green = tuple(k for k, v in OBJECTIVES.items() if v == "GREEN" or v.startswith("GREEN_"))
    pending = tuple(k for k, v in OBJECTIVES.items() if not (v == "GREEN" or v.startswith("GREEN_")))
    return {
        "green_objectives": fully_green,
        "pending_objectives": pending,
        "app_main_mutation_claimed": True,
        "app_preprod_reactivated": False,
        "global_prod_green": False,
        "automatic_prod_promotion_allowed": False,
        "status": "APP_RPC_SOURCE_PROMOTION_GREEN_AUTH_HTTP_E2E_AND_GLOBAL_GAPS_OPEN",
    }
