from __future__ import annotations

AUDIT = {
    "captured_at": "2026-09-13",
    "mode": "READ_ONLY",
    "app_main_sha": "95106d8e792257f809033486b7025d81665ea83b",
    "app_preprod_reactivated": False,
    "app_main_modified": False,
    "APP_003_expedientes": {
        "status": "READ_ONLY_AUDIT_GREEN",
        "live_rows": {"expedientes": 46, "expediente_personas": 17, "expediente_stage_history": 24},
        "list_server_present": True,
        "workspace_server_present": True,
        "consistency_server_present": True,
        "actions_server_present": True,
        "stage_server_present": True,
        "update_server_present": True,
        "direct_create_user_rpc_pending_gateway_migration": True,
        "direct_update_user_rpc_pending_gateway_migration": True,
        "lifecycle_uses_version_check_and_confirmation": True,
    },
    "APP_004_tasks_notifications": {
        "status": "READ_ONLY_AUDIT_GREEN_WITH_NOTIFICATION_GATEWAY_GAP",
        "live_rows": {"tareas": 88, "notification_state": 4},
        "task_create_server_present": True,
        "task_get_server_present": True,
        "task_update_server_present": True,
        "task_reassign_server_present": True,
        "notification_list_user_rpc_still_direct": True,
        "notification_mark_user_rpc_still_direct": True,
        "notification_server_wrappers_missing": True,
    },
    "APP_005_documents": {
        "status": "READ_ONLY_AUDIT_GREEN",
        "document_actions_edge_active": True,
        "document_intelligence_edge_active": True,
        "document_extract_edge_active": True,
        "document_reread_edge_active": True,
        "document_auto_ingest_edge_active": True,
        "document_existing_backfill_edge_active": True,
        "gateway_document_routes_present": True,
    },
    "APP_006_signatures": {
        "status": "READ_ONLY_AUDIT_GREEN_WITH_CREATE_GATEWAY_GAP",
        "live_rows": {"firmas": 0},
        "list_server_present": True,
        "scope_server_present": True,
        "history_server_present": True,
        "schedule_server_present": True,
        "confirm_server_present": True,
        "close_server_present": True,
        "create_user_rpc_still_direct": True,
        "create_server_wrapper_missing": True,
        "signature_human_gate_preserved": True,
    },
    "APP_007_communications": {
        "status": "PARTIAL_PROD_WIRING_MISMATCH",
        "prod_edge_active": True,
        "prod_edge_slug": "fenix-communications-gateway",
        "shell_calls_test_slug": "fenix-communications-gateway-test",
        "shell_role_gate_direction_only": True,
        "prepare_then_authorize_flow_present": True,
        "send_ui_mode_simulated": True,
        "automatic_real_send_claimed": False,
    },
}


def assess() -> dict:
    return {
        "APP_003_green": AUDIT["APP_003_expedientes"]["status"] == "READ_ONLY_AUDIT_GREEN",
        "APP_004_audit_green": AUDIT["APP_004_tasks_notifications"]["status"].startswith("READ_ONLY_AUDIT_GREEN"),
        "APP_005_green": AUDIT["APP_005_documents"]["status"] == "READ_ONLY_AUDIT_GREEN",
        "APP_006_audit_green": AUDIT["APP_006_signatures"]["status"].startswith("READ_ONLY_AUDIT_GREEN"),
        "APP_007_green": False,
        "APP_007_blocker": "production shell targets -test communications gateway while production gateway exists",
        "app_main_unchanged": not AUDIT["app_main_modified"],
        "app_preprod_stays_cancelled": not AUDIT["app_preprod_reactivated"],
        "safe_next": "audit_reports_and_crm_sync_then_fix_communications_on_parallel_branch",
        "status": "APP_003_006_AUDIT_GREEN_APP_007_WIRING_GAP",
    }
