from __future__ import annotations

OBJECTIVES = {
    "APP_001_inventory": "GREEN",
    "CRM_001_inventory": "GREEN",
    "APP_002_auth_rpc_security": "PARTIAL_LIVE_WRAPPERS_HARDENED_ROUTING_V17_DEPLOYED_APP_STILL_DIRECT_RPC_HTTP_E2E_OPEN",
    "APP_003_expedientes": "GREEN_BRANCH_AND_LIVE_RPC_PARITY_HTTP_E2E_SUBGAP",
    "APP_004_tasks_notifications": "GREEN_BRANCH_AND_LIVE_RPC_PARITY_HTTP_E2E_SUBGAP",
    "APP_005_documents": "GREEN",
    "APP_006_signatures": "GREEN_BRANCH_AND_LIVE_RPC_PARITY_HTTP_E2E_SUBGAP",
    "APP_007_communications": "GREEN_CORE_GATEWAY_WITH_OPTIONAL_ADVICE_FAIL_SOFT",
    "APP_008_reports": "GREEN",
    "CRM_002_sync_consistency": "GREEN_LEGACY_SYNC_RETIRED_FAIL_CLOSED",
    "APP_009_carlos_cerebro_access": "PARTIAL_PROFILE_LAUNCHER_BRANCH_GREEN_DEPLOYED_CONSOLE_URL_MISSING",
    "APP_010_cerebro_gateway": "PARTIAL_HTTP_AND_WEB_UI_GREEN_DEPLOYED_URL_MISSING",
    "APP_011_old_new_rollback_promotion": "BLOCKED_DEPLOYED_APP_CALLER_RETIREMENT_HTTP_E2E_AND_HUMAN_GATE",
}

BLOCKERS = {
    "rpc_live_migration": {
        "authorized": True,
        "remaining_server_wrappers": 0,
        "server_wrappers_live": True,
        "server_wrappers_security_definer": True,
        "server_wrappers_service_role_only": True,
        "unknown_actor_fail_closed_all_five": True,
        "null_actor_guard_migration": "harden_server_wrappers_null_actor_guard_20260914",
        "exp_create_null_actor_guard": True,
        "sign_create_null_actor_guard": True,
        "app_gateway_live_version": 17,
        "app_gateway_required_routes_live": True,
        "runner_direct_callers_before": 10,
        "runner_direct_callers_after": 0,
        "persisted_branch_direct_callers_zero": True,
        "live_deploy_channel": "GITHUB_PAGES_GH_PAGES",
        "live_deployed_source_sha": "c7a15cff9a387f1f142c8eeb06fd83a799e85a61",
        "live_deployed_source_date": "2026-09-11",
        "live_deployed_contact_direct_rpc_observed": "fenix_prod_contact_create_v2",
        "live_deployed_app_is_pre_rpc_migration_branch": True,
        "live_direct_callers_zero_proven": False,
        "live_rpc_old_new_parity_proven": True,
        "live_rpc_old_new_parity_transaction_rolled_back": True,
        "live_rpc_old_new_parity_cases": (
            "notifications_list",
            "notification_mark",
            "contact_create",
            "exp_create",
            "sign_create",
        ),
        "live_gateway_http_e2e_proven": False,
        "authenticated_execute_revoke_allowed": False,
        "execution_channel_blocked_prior_attempts": True,
        "execution_channel_available_for_authorized_gateway_deploy": True,
        "branch_persisted_migrations": {
            "notifications_list": True,
            "notification_mark": True,
            "signature_create": True,
            "contact_create": True,
            "expediente_create": True,
            "branch_head": "b1b6fb5404a4704c5d637fc770fc90e9f2eb8312",
            "audit_ci_run": 34786441006,
            "audit_ci_success": True,
            "main_modified": False,
            "legacy_authenticated_execute_revoked": False,
        },
    },
    "communications": {
        "prod_gateway_exists": True,
        "prod_gateway_version": 8,
        "app_shell_targets_prod_gateway": True,
        "prepare_send_contract_aligned": True,
        "real_send_path_owned_by_gateway": True,
        "real_send_providers": ("brevo", "whatsapp"),
        "assistant_dependency": "fenix-expediente-assistant-test",
        "assistant_present_in_current_prod_edge_inventory": False,
        "assistant_is_optional_draft_enrichment_only": True,
        "assistant_failure_is_fail_soft": True,
        "communications_core_operational_without_assistant": True,
        "real_send_claimed": False,
    },
    "cerebro_console": {
        "logical_gateway_contract_green": True,
        "http_surface_green": True,
        "pipeline_audit_path_green": True,
        "trusted_upstream_identity_boundary_green": True,
        "browser_identity_header_trusted": False,
        "app_profile_surface_found": True,
        "internal_console_route_present": True,
        "internal_console_route": "/cerebro",
        "branch_profile_launcher_present": True,
        "web_shell_fail_closed_without_gateway_url": True,
        "deployed_authenticated_console_url_proven": False,
        "deployed_profile_launcher_proven": False,
        "dead_link_allowed": False,
    },
    "credential_registry": {
        "metadata_only_registry_present": True,
        "raw_secret_fields_forbidden_by_validator": True,
        "opaque_provider_managed_credentials_supported": True,
        "vault_refs_supported": True,
        "raw_values_in_registry_allowed": False,
    },
    "global_pre_app_closure": {
        "security_global_green": False,
        "recovery_global_green": False,
        "observability_global_green": False,
        "finops_global_green": False,
        "promotion_human_gate_required": True,
    },
}


def assess() -> dict:
    fully_green = tuple(k for k, v in OBJECTIVES.items() if v == "GREEN" or v.startswith("GREEN_"))
    pending = tuple(k for k, v in OBJECTIVES.items() if not (v == "GREEN" or v.startswith("GREEN_")))
    return {
        "green_objectives": fully_green,
        "pending_objectives": pending,
        "app_main_mutation_claimed": False,
        "app_preprod_reactivated": False,
        "global_prod_green": False,
        "automatic_prod_promotion_allowed": False,
        "status": "APP_CRM_COMMUNICATIONS_CORE_GREEN_LIVE_APP_STILL_PRE_MIGRATION_FAIL_CLOSED",
    }
