from __future__ import annotations

# Canonical grouped closure objectives for the final green loop.
# Fail-closed by design: no objective group becomes GREEN from structural proof alone.
# This module performs no external mutation and authorizes no PROD promotion.

OBJECTIVE_GROUPS = {
    "SECURITY": {
        "target": "supabase_security_review_green",
        "status": "PARTIAL_DEPLOYED_APP_PRE_MIGRATION_AND_ADVISOR_DISPOSITION_OPEN",
        "green": False,
        "completed": (
            "15_authenticated_security_definer_rpcs_inventory",
            "15_live_acl_and_definition_fingerprints_captured",
            "33_edge_surfaces_read_only_inspected",
            "6_current_frontend_direct_callers_verified_at_app_head",
            "9_remaining_mutators_frontend_negative_search_recorded_fail_closed",
            "9_remaining_mutators_expanded_repo_negative_search_recorded_fail_closed",
            "live_implementation_shape_15_of_15_classified",
            "2_direct_server_delegations_identified",
            "15_mutator_8_dimension_parity_matrix_created",
            "13_missing_or_non_equivalent_server_wrapper_contracts_defined",
            "all_mutator_families_semantic_lab_contracts_covered",
            "chat_contacts_exp_create_inmo_followup_lab_replay_green",
            "notifications_profile_socials_profile_update_signature_lab_contracts_green",
            "signature_required_gate_preserved",
            "corrected_frontend_caller_blob_shas_canonicalized",
            "44_of_44_fenix_prod_tables_rls_enabled_live",
            "five_target_server_wrappers_live_security_definer_service_role_only",
            "five_target_server_wrappers_unknown_actor_fail_closed",
            "exp_create_and_sign_create_null_actor_guard_hardened_live",
            "five_target_old_new_rpc_parity_green_in_rolled_back_prod_transaction",
            "app_gateway_v17_required_target_routes_live",
            "app_branch_persisted_direct_prod_rpc_callers_zero_ci_34786441006",
            "live_deploy_channel_identified_as_github_pages_gh_pages",
            "live_deployed_source_sha_c7a15cff9a387f1f142c8eeb06fd83a799e85a61",
            "live_deployed_contact_direct_rpc_fenix_prod_contact_create_v2_confirmed",
            "supabase_security_advisor_inventory_captured_2026_09_14",
            "44_rls_enabled_no_policy_info_findings_classified_fail_closed_not_open_access",
            "24_authenticated_security_definer_execute_warnings_captured",
            "pg_net_public_extension_namespace_warning_captured_version_0_20_4",
            "pg_net_function_namespace_net_confirmed_read_only",
            "leaked_password_protection_disabled_warning_captured",
            "blind_bulk_security_changes_rejected",
        ),
        "remaining": (
            "deploy_or_promote_reviewed_rpc_migration_without_bypassing_human_prod_gate",
            "live_deployed_app_direct_caller_zero_evidence_after_promotion",
            "authenticated_http_gateway_e2e_for_target_routes",
            "rollback_evidence_for_full_http_write_path",
            "caller_retirement_evidence_before_any_legacy_privilege_change",
            "controlled_disposition_of_24_security_definer_authenticated_execute_warnings_after_live_caller_retirement",
            "pg_net_extension_namespace_dependency_backup_and_rebuild_review_before_any_move",
            "leaked_password_protection_enablement_when_auth_config_write_channel_is_available",
        ),
    },
    "RECOVERY": {
        "target": "provider_restore_and_prod_rollback_green",
        "status": "PARTIAL_ZERO_COST_RESTORE_TARGET_NOT_AVAILABLE",
        "green": False,
        "completed": (
            "immutable_git_source_snapshot",
            "runtime_rebuild_rehearsal_ci",
            "non_destructive_rollback_rehearsal_ci",
            "live_supabase_project_and_branch_inventory_captured",
            "prod_branch_inventory_revalidated_2026_09_14_main_only",
            "legacy_branch_inventory_revalidated_2026_09_14_zero_branches",
            "legacy_core_preprod_surface_preserved",
            "isolated_restore_plan_defined",
            "unsafe_existing_restore_targets_rejected",
            "failed_paid_branch_attempt_audited_and_deleted",
            "paid_branch_cost_stopped_after_cleanup",
            "free_security_lab_namespace_established_non_restore_equivalent",
        ),
        "remaining": (
            "isolated_non_prod_restore_target_proven_without_unapproved_cost",
            "completed_provider_restore",
            "restore_integrity_check",
            "application_smoke_after_restore",
            "cleanup_or_retention_evidence_for_successful_restore",
            "real_release_or_provider_rollback_target_proven",
        ),
    },
    "OBSERVABILITY": {
        "target": "per_engine_logs_metrics_incidents_complete",
        "status": "PARTIAL_PROD_LEGACY_SCOPE_REVALIDATED_OFFLOAD_WIRING_OPEN",
        "green": False,
        "completed": (
            "177_engine_structural_observability_contract",
            "177_engine_lab_log_metric_incident_runtime_proven",
            "shared_scope_fields_company_engine_environment_version",
            "selected_family_live_evidence",
            "prod_live_observability_tables_read_only_verified",
            "prod_current_tables_missing_full_multiempresa_scope_confirmed",
            "prod_legacy_observability_scope_revalidated_2026_09_14",
            "parallel_multiempresa_observability_envelope_defined",
            "parallel_observability_mirror_lab_green",
            "parallel_prod_mirroring_wiring_gate_green_fail_closed",
            "seo_retained_prod_health_5_of_5_success",
            "seo_parallel_incident_classifier_green",
            "seo_retained_run_replay_green",
            "seo_nonprod_incident_capture_fixture_green",
            "linkedin_retained_health_execution_green",
            "youtube_health_reauthorization_green",
            "youtube_health_connection_rewired_green",
            "youtube_health_scenario_returned_inactive_after_controlled_attempt",
        ),
        "remaining": (
            "parallel_prod_mirroring_wiring_without_legacy_table_breakage",
            "persistent_zero_cost_auxiliary_sink_for_prod_mirror",
            "per_engine_prod_live_log_coverage",
            "per_engine_prod_live_metric_coverage",
            "per_engine_prod_live_incident_coverage",
            "youtube_retained_metric_execution_or_explicit_approved_absence_policy",
            "seo_prod_incident_capture_evidence_after_safe_wiring",
        ),
    },
    "FINOPS": {
        "target": "monthly_cost_measured",
        "status": "PARTIAL_HISTORICAL_NOTION_PRICE_ANCHORED_CURRENT_NOTION_AND_GCP_EXACT_AMOUNTS_OPEN",
        "green": False,
        "completed": (
            "supabase_monthly_cost_measured",
            "make_monthly_cost_measured",
            "canva_monthly_cost_measured",
            "hostinger_business_email_monthly_cost_measured",
            "notion_authoritative_email_confirms_plus_plan_and_three_seats",
            "notion_authoritative_email_confirms_recent_payment_failure_without_exact_amount",
            "notion_authoritative_historical_trial_price_2025_04_04_eur_11_50_per_member_three_members_eur_34_50_month",
            "notion_historical_price_not_misclassified_as_current_2026_cost",
            "google_cloud_authoritative_email_confirms_paid_billing_and_payment_problem_without_exact_amount",
            "google_cloud_recent_billing_email_search_found_no_exact_amount",
            "provider_to_family_attribution_model_defined_without_fake_allocation",
            "no_free_tier_overage_claim_without_evidence",
            "incremental_cerebro_cost_target_zero_eur",
        ),
        "remaining": (
            "notion_current_2026_exact_monthly_amount_from_authoritative_billing_source",
            "google_cloud_exact_monthly_amount_or_zero_cost_proof_from_authoritative_billing_source",
            "usage_based_family_or_engine_cost_attribution_where_real_usage_evidence_exists",
        ),
    },
    "PROMOTION": {
        "target": "prod_candidate_human_gated",
        "status": "BLOCKED_BY_UPSTREAM_GAPS",
        "green": False,
        "completed": (
            "factory_ci_green",
            "177_lab_green_baseline",
            "promotion_gate_fail_closed",
        ),
        "remaining": (
            "security_green",
            "recovery_green",
            "observability_green",
            "finops_green",
            "human_gate_for_final_prod_promotion",
        ),
    },
}

EXECUTION_ORDER = ("SECURITY", "RECOVERY", "OBSERVABILITY", "FINOPS", "PROMOTION")


def assess_objective_groups() -> dict:
    groups = {name: OBJECTIVE_GROUPS[name] for name in EXECUTION_ORDER}
    green = tuple(name for name, row in groups.items() if row["green"])
    pending = tuple(name for name, row in groups.items() if not row["green"])
    return {
        "execution_order": EXECUTION_ORDER,
        "groups": groups,
        "green_groups": green,
        "pending_groups": pending,
        "all_green": not pending,
        "prod_candidate_allowed": False,
        "automatic_prod_promotion_allowed": False,
        "status": "GREEN_LOOP_IN_PROGRESS" if pending else "PROD_CANDIDATE_HUMAN_GATED",
    }
