from __future__ import annotations

# Canonical grouped closure objectives for the final green loop.
# Fail-closed by design: no objective group becomes GREEN from structural proof alone.
# This module performs no external mutation and authorizes no PROD promotion.

OBJECTIVE_GROUPS = {
    "SECURITY": {
        "target": "supabase_security_review_green",
        "status": "PARTIAL_ANON_SECDEF_INCIDENT_CLOSED_WRITE_E2E_PRIVILEGE_RETIREMENT_AND_REMAINING_ADVISORS_OPEN",
        "green": False,
        "human_required": ("HIGH_RISK", "SECURITY_INCIDENT"),
        "completed": (
            "15_authenticated_security_definer_rpcs_inventory",
            "15_live_acl_and_definition_fingerprints_captured",
            "33_edge_surfaces_read_only_inspected",
            "6_current_frontend_direct_callers_verified_at_app_head",
            "9_remaining_mutators_frontend_negative_search_recorded_fail_closed",
            "9_remaining_mutators_expanded_repo_negative_search_recorded_fail_closed",
            "live_implementation_shape_15_of_15_classified",
            "2_direct_server_delegations_identified",
            "15_mutator_8_dimension_parity_matrix_created",
            "13_missing_or_non_equivalent_server_wrapper_contracts_defined",
            "all_mutator_families_semantic_lab_contracts_covered",
            "chat_contacts_exp_create_inmo_followup_lab_replay_green",
            "notifications_profile_socials_profile_update_signature_lab_contracts_green",
            "signature_required_gate_preserved",
            "corrected_frontend_caller_blob_shas_canonicalized",
            "44_of_44_fenix_prod_tables_rls_enabled_live",
            "five_target_server_wrappers_live_security_definer_service_role_only",
            "five_target_server_wrappers_unknown_actor_fail_closed",
            "exp_create_and_sign_create_null_actor_guard_hardened_live",
            "five_target_old_new_rpc_parity_green_in_rolled_back_prod_transaction",
            "app_gateway_v17_required_target_routes_live",
            "authenticated_gateway_five_target_e2e_plan_locked_fail_closed",
            "four_write_targets_without_proven_http_cleanup_route_recorded",
            "dedicated_cerebro_ops_identity_created_through_supported_auth_dashboard",
            "dedicated_cerebro_ops_identity_authenticated_in_live_app",
            "dedicated_cerebro_ops_notifications_read_path_browser_verified_green",
            "app_branch_persisted_direct_prod_rpc_callers_zero_ci_34786441006",
            "reviewed_rpc_migration_pr_376_human_authorized_and_merged",
            "app_main_merge_sha_dd09153a6d025d9cc75eb2c14e776a9e5bd8e16c",
            "prod_live_deploy_run_34790008072_success",
            "prod_runtime_smoke_run_34790008059_success",
            "prod_runtime_smoke_exact_live_sha_and_gateway_boundary_green",
            "prod_live_deploy_asserted_no_preprod_backend",
            "gh_pages_prod_snapshot_c8a4bc720ce91eb46ed811c506623c265d043594",
            "prod_source_sha_matches_main_merge_dd09153a6d025d9cc75eb2c14e776a9e5bd8e16c",
            "live_deployed_source_direct_prod_rpc_search_zero_after_promotion",
            "live_gateway_http_health_200_contract_v3",
            "live_gateway_target_route_without_identity_fails_closed_401",
            "eight_legacy_rpc_retirement_signatures_live_verified",
            "eight_legacy_rpc_retirement_sql_and_rollback_prepared_not_applied",
            "cloudflare_two_workers_builds_success_on_promoted_sha",
            "cloudflare_pages_read_only_inventory_20260914_green",
            "cloudflare_pages_project_only_pages_dev_domain_no_app_custom_domain",
            "cloudflare_pages_source_main_but_preview_deployments_disabled",
            "cloudflare_audit_branch_preview_skip_classified_policy_not_app_runtime_failure",
            "cloudflare_pages_build_command_next_on_pages_mismatches_vite_app_recorded",
            "cloudflare_pages_noncanonical_parallel_role_proven_preserved_untouched",
            "cloudflare_read_only_inventory_raw_secret_exposure_security_incident_recorded_without_persisting_value",
            "supabase_security_advisor_inventory_captured_2026_09_14",
            "44_rls_enabled_no_policy_info_findings_classified_fail_closed_not_open_access",
            "24_authenticated_security_definer_execute_warnings_captured",
            "24_security_definer_warnings_partitioned_8_legacy_7_read_session_9_mutators",
            "nine_remaining_mutator_names_default_branch_negative_search_recorded_fail_closed",
            "pg_net_public_extension_namespace_warning_captured_version_0_20_4",
            "pg_net_function_namespace_net_confirmed_read_only",
            "leaked_password_protection_disabled_warning_captured",
            "leaked_password_protection_supported_remediation_path_documented",
            "blind_bulk_security_changes_rejected",
            "anon_secdef_three_rpc_prechange_snapshot_and_rollback_2026_09_16",
            "anon_secdef_three_rpc_supported_edge_callers_verified_service_role_2026_09_16",
            "anon_secdef_three_rpc_prod_acl_remediation_applied_2026_09_16",
            "anon_secdef_three_rpc_post_acl_anon_false_authenticated_false_service_role_true",
            "supabase_advisor_anon_security_definer_findings_zero_2026_09_16",
            "authenticated_security_definer_findings_reduced_19_to_16_2026_09_16",
        ),
        "remaining": (
            "authenticated_http_gateway_write_e2e_for_target_routes_after_safe_cleanup_strategy",
            "rollback_or_non_durable_cleanup_evidence_for_full_http_write_path",
            "selective_retirement_of_only_migrated_legacy_authenticated_execute_after_http_gate",
            "post_retirement_gateway_e2e_and_advisor_recheck",
            "caller_and_contract_disposition_of_16_remaining_authenticated_security_definer_surfaces",
            "cloudflare_secret_consumer_inventory_rotation_and_post_rotation_verification",
            "pg_net_extension_namespace_dependency_backup_and_rebuild_review_before_any_move",
            "leaked_password_protection_enablement_when_auth_config_write_channel_is_available",
            "two_mutable_search_path_function_warnings_disposition",
        ),
    },
    "RECOVERY": {
        "target": "provider_restore_and_prod_rollback_green",
        "status": "PARTIAL_APP_SOURCE_ROLLBACK_GREEN_PROVIDER_DB_RESTORE_MONEY_LIMIT",
        "green": False,
        "human_required": ("MONEY_LIMIT",),
        "completed": (
            "immutable_git_source_snapshot",
            "runtime_rebuild_rehearsal_ci",
            "non_destructive_rollback_rehearsal_ci",
            "live_supabase_project_and_branch_inventory_captured",
            "prod_branch_inventory_revalidated_2026_09_14_main_only",
            "legacy_branch_inventory_revalidated_2026_09_14_zero_branches",
            "legacy_core_preprod_surface_preserved",
            "isolated_restore_plan_defined",
            "unsafe_existing_restore_targets_rejected",
            "failed_paid_branch_attempt_audited_and_deleted",
            "paid_branch_cost_stopped_after_cleanup",
            "free_security_lab_namespace_established_non_restore_equivalent",
            "zero_cost_local_ci_snapshot_manifest_sha256_green",
            "zero_cost_local_ci_backup_integrity_green",
            "zero_cost_local_ci_isolated_restore_integrity_green",
            "zero_cost_local_ci_post_restore_smoke_green",
            "zero_cost_local_ci_cleanup_green",
            "zero_cost_local_ci_recovery_run_34788667726_green",
            "previous_prod_source_c7a15cff9a387f1f142c8eeb06fd83a799e85a61_resolves",
            "app_previous_prod_source_rollback_rehearsal_run_34808719859_green",
            "app_rollback_artifact_10333274904_sha256_1d461022a00576a41acac8857af809aeff7666e0b4cdbd541f6fc67f6e4e787a",
            "real_release_or_provider_rollback_target_proven",
            "supabase_restore_to_new_project_paid_and_additional_monthly_expense_documented",
            "supabase_pitr_paid_addon_documented",
            "no_existing_zero_incremental_cost_isolated_provider_target_proven",
        ),
        "remaining": (
            "money_limit_authorization_or_zero_incremental_cost_isolated_provider_target",
            "completed_provider_restore",
            "provider_restore_integrity_check",
            "application_smoke_after_provider_restore",
            "cleanup_or_retention_evidence_for_successful_provider_restore",
        ),
    },
    "OBSERVABILITY": {
        "target": "per_engine_logs_metrics_incidents_complete",
        "status": "PARTIAL_ZERO_COST_AUX_SINK_LAB_GREEN_YOUTUBE_GREEN_PERSISTENT_PROD_SINK_OPEN",
        "green": False,
        "human_required": (),
        "completed": (
            "177_engine_structural_observability_contract",
            "177_engine_lab_log_metric_incident_runtime_proven",
            "shared_scope_fields_company_engine_environment_version",
            "selected_family_live_evidence",
            "prod_live_observability_tables_read_only_verified",
            "prod_current_tables_missing_full_multiempresa_scope_confirmed",
            "prod_legacy_observability_scope_revalidated_2026_09_14",
            "parallel_multiempresa_observability_envelope_defined",
            "parallel_observability_mirror_lab_green",
            "parallel_prod_mirroring_wiring_gate_green_fail_closed",
            "zero_cost_jsonl_auxiliary_sink_implemented",
            "zero_cost_jsonl_scope_company_engine_environment_version_enforced",
            "zero_cost_jsonl_log_metric_incident_coverage_green",
            "zero_cost_jsonl_secret_like_fields_rejected",
            "zero_cost_jsonl_corruption_fails_closed",
            "zero_cost_jsonl_replay_and_scope_green",
            "zero_cost_observability_sink_ci_run_34788667726_green",
            "seo_retained_prod_health_5_of_5_success",
            "seo_parallel_incident_classifier_green",
            "seo_retained_run_replay_green",
            "seo_nonprod_incident_capture_fixture_green",
            "linkedin_retained_health_execution_green",
            "make_datastore_171764_shared_core_health_and_dedupe_inventory_captured",
            "make_datastore_172319_temp_test_schema_audit_inventory_captured",
            "make_existing_stores_rejected_as_unproven_multiempresa_prod_sink",
            "make_scope_probe_scenario_creation_refused_precreated_datastore_required_no_record_written",
            "youtube_health_activation_attempt_20260914_failed_closed_connection_verify_400_zero_operations_zero_credits",
            "youtube_oauth_reauthorized_supported_user_flow",
            "youtube_health_manual_execution_bcdc124704c147daafc12363cee431a5_success_three_operations",
            "advisory_preprod_structured_stdout_sink_green_2026_09_16",
            "advisory_preprod_cloud_logging_persistent_coverage_green_run_35143362166",
            "advisory_preprod_observability_artifact_10466262341_digest_sha256_0140d478632dea724437ccfc320e02e8153b8e82f4dc2dd5eab98be25b59110a",
            "advisory_preprod_observability_repeat_green_run_35143638040",
        ),
        "remaining": (
            "parallel_prod_mirroring_wiring_without_legacy_table_breakage",
            "persistent_zero_cost_auxiliary_sink_for_prod_mirror_deployment",
            "per_engine_prod_live_log_coverage",
            "per_engine_prod_live_metric_coverage",
            "per_engine_prod_live_incident_coverage",
            "youtube_retained_metric_execution_or_explicit_approved_absence_policy",
            "seo_prod_incident_capture_evidence_after_safe_wiring",
        ),
    },
    "FINOPS": {
        "target": "monthly_cost_measured",
        "status": "PARTIAL_NOTION_CURRENT_AMOUNT_CAPTURED_GCP_MONTHLY_PERIOD_TOTAL_OPEN",
        "green": False,
        "human_required": (),
        "completed": (
            "supabase_monthly_cost_measured",
            "make_monthly_cost_measured",
            "canva_monthly_cost_measured",
            "hostinger_business_email_monthly_cost_measured",
            "notion_authoritative_email_confirms_plus_plan_and_three_seats",
            "notion_authoritative_email_confirms_recent_payment_failure_without_exact_amount",
            "notion_authoritative_historical_trial_price_2025_04_04_eur_11_50_per_member_three_members_eur_34_50_month",
            "notion_historical_price_not_misclassified_as_current_2026_cost",
            "notion_cost_matrix_2026_08_26_business_reference_20_usd_per_member_month_found",
            "notion_business_reference_not_misclassified_as_exact_current_invoice",
            "notion_current_billing_ui_user_reported_68_97_eur_month_two_users",
            "notion_plan_rightsizing_deferred_until_after_closure_loop",
            "google_cloud_authoritative_email_confirms_paid_billing_and_payment_problem_without_exact_amount",
            "google_cloud_recent_billing_email_search_found_no_exact_amount",
            "google_cloud_billing_ui_snapshot_fenix_trading_lab_charge_0_34_eur",
            "google_cloud_fenix_capital_snapshot_charge_0_00_eur",
            "google_cloud_monthly_period_total_not_inferred_from_snapshot",
            "provider_to_family_attribution_model_defined_without_fake_allocation",
            "no_free_tier_overage_claim_without_evidence",
            "incremental_cerebro_cost_target_zero_eur",
        ),
        "remaining": (
            "google_cloud_exact_monthly_period_total_or_zero_cost_proof_from_authoritative_billing_source",
            "usage_based_family_or_engine_cost_attribution_where_real_usage_evidence_exists",
        ),
    },
    "PROMOTION": {
        "target": "prod_candidate_human_gated",
        "status": "BLOCKED_BY_UPSTREAM_GAPS",
        "green": False,
        "human_required": (),
        "completed": (
            "factory_ci_green",
            "177_lab_green_baseline",
            "promotion_gate_fail_closed",
            "app_rpc_source_promotion_human_gate_completed",
        ),
        "remaining": (
            "security_green",
            "recovery_green",
            "observability_green",
            "finops_green",
            "human_gate_for_final_prod_promotion",
        ),
    },
}

EXECUTION_ORDER = ("SECURITY", "RECOVERY", "OBSERVABILITY", "FINOPS", "PROMOTION")


def assess_objective_groups() -> dict:
    groups = {name: OBJECTIVE_GROUPS[name] for name in EXECUTION_ORDER}
    green = tuple(name for name, row in groups.items() if row["green"])
    pending = tuple(name for name, row in groups.items() if not row["green"])
    human_required = tuple(
        (name, code)
        for name, row in groups.items()
        for code in row.get("human_required", ())
    )
    return {
        "execution_order": EXECUTION_ORDER,
        "groups": groups,
        "green_groups": green,
        "pending_groups": pending,
        "human_required": human_required,
        "all_green": not pending,
        "prod_candidate_allowed": False,
        "automatic_prod_promotion_allowed": False,
        "status": "GREEN_LOOP_IN_PROGRESS" if pending else "PROD_CANDIDATE_HUMAN_GATED",
    }
