import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")??"",A=Deno.env.get("SUPABASE_ANON_KEY")??"",N=Deno.env.get("NOTION_TOKEN")??"";
const NV="2025-09-03",LEARN_DS="56665cb7-4277-4557-acff-f6fd46601e77";
const ORIGINS=new Set(["https://app.fenixcapital.es"]);const nh={Authorization:`Bearer ${N}`,"Notion-Version":NV,"Content-Type":"application/json"};
function cors(req:Request){const o=req.headers.get('origin')??'',ao=ORIGINS.has(o)?o:'https://app.fenixcapital.es';return{"access-control-allow-origin":ao,"access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"authorization,apikey,content-type,x-client-info","access-control-max-age":"86400","vary":"Origin","cache-control":"no-store","x-fenix-env":"PROD"};}
const J=(req:Request,d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors(req),"content-type":"application/json; charset=utf-8"}});
function pathOf(req:Request){const p=new URL(req.url).pathname,m="/fenix-ana-canonical",i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||"/"):p;}
function plain(p:any){if(!p)return null;if(p.type==='title')return(p.title??[]).map((x:any)=>x.plain_text??'').join('');if(p.type==='rich_text')return(p.rich_text??[]).map((x:any)=>x.plain_text??'').join('');if(p.type==='select')return p.select?.name??null;if(p.type==='checkbox')return Boolean(p.checkbox);if(p.type==='number')return p.number??null;if(p.type==='date')return p.date?.start??null;return null;}
async function nq(filter:any,pageSize=25){const r=await fetch(`https://api.notion.com/v1/data_sources/${LEARN_DS}/query`,{method:'POST',headers:nh,body:JSON.stringify({page_size:pageSize,filter,sorts:[{property:'Fecha decisión',direction:'descending'}]})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(`notion_query_${r.status}_${b?.code??'error'}`);return b?.results??[];}
function item(x:any){const p=x.properties??{};return{id:x.id,domain:String(plain(p.Dominio)||'Operaciones'),rule:String(plain(p['Regla aprendida'])||plain(p['Decisión tomada'])||''),source:String(plain(p.Fuente)||''),confidence:Number(plain(p['Confianza aprendizaje %'])??100),exception:Boolean(plain(p['Es excepción'])),test:Boolean(plain(p['Es TEST'])),approved:Boolean(plain(p['Aprobación canónica'])),state:String(plain(p.Estado)||''),date:String(plain(p['Fecha decisión'])||plain(p.Fecha)||x.last_edited_time||'')};}
Deno.serve(async(req:Request)=>{try{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!U||!A||!N)return J(req,{ok:false,error:'server_config_missing'},503);const auth=req.headers.get('authorization')??'';if(!auth.toLowerCase().startsWith('bearer '))return J(req,{ok:false,error:'unauthorized'},401);const ac=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const c=await ac.rpc('fenix_prod_session_context');if(c.error)return J(req,{ok:false,error:'session_context_failed'},500);const ctx:any=c.data;if(!ctx?.actor_code)return J(req,{ok:false,error:'identity_not_linked'},403);const path=pathOf(req);if(req.method!=='GET'||path!=='/rules')return J(req,{ok:false,error:'not_found'},404);const u=new URL(req.url),domain=String(u.searchParams.get('domain')??'').trim();if(!domain)return J(req,{ok:false,error:'domain_required'},400);const rows=await nq({and:[{property:'Dominio',select:{equals:domain}},{property:'Aprobación canónica',checkbox:{equals:true}},{property:'Estado',select:{equals:'Aplicada'}}]});const mapped=rows.map(item).filter((x:any)=>x.rule.trim().length>0&&!x.test);const items=mapped.filter((x:any)=>!x.exception),precedents=mapped.filter((x:any)=>x.exception);return J(req,{ok:true,status:200,domain,items,precedents,count:items.length,precedent_count:precedents.length,total_count:mapped.length,actor:{actor_code:ctx.actor_code,role:ctx.role},source:'Aprendizaje operativo · Fénix Uno',canonical_only:true,exception_policy:'precedent_requires_context_review',test_rows_allowed:false,production_policy:'exclude_test_rows'});}catch(e){console.error('fenix-ana-canonical',e instanceof Error?e.message:String(e));return J(req,{ok:false,error:'canonical_reader_exception'},500)}});